//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETHOADON
    {
        public int ID { get; set; }
        public int IDChiTietMatHang { get; set; }
        public int IDHoaDon { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<bool> STATUS { get; set; }
    
        public virtual CHITIETMATHANG CHITIETMATHANG { get; set; }
        public virtual HOADON HOADON { get; set; }
    }
}
