//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_Server_SHOP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETHOADON
    {
        public string ID { get; set; }
        public string IDChiTietMatHang { get; set; }
        public string IDHoaDon { get; set; }
        public Nullable<int> SoLuong { get; set; }
    
        public virtual CHITIETMATHANG CHITIETMATHANG { get; set; }
        public virtual HOADON HOADON { get; set; }
    }
}
