//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_Server_SHOP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBLOAIHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SUBLOAIHANG()
        {
            this.MATHANGs = new HashSet<MATHANG>();
        }
    
        public string ID { get; set; }
        public string IDLoaiHang { get; set; }
        public string TenLoai { get; set; }
        public string MoTa { get; set; }
    
        public virtual LOAIHANG LOAIHANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MATHANG> MATHANGs { get; set; }
    }
}
